### ISSUE TITLE
The approvals attribute on app.py is not properly defined and initialized, install pipeline doesn't start. - cli 10.4.1

### ISSUE THREAD

**Issue by lu4t** [ibm-mas/installer#1134]
As of MAS CLI v10.4.1 you get this error when running a clean mas install:

```
Traceback (most recent call last):
  File "/opt/app-root/bin/mas-cli", line 54, in <module>
    app.install(argv[2:])
  File "/opt/app-root/lib64/python3.9/site-packages/mas/cli/install/app.py", line 1033, in install
    self.setupApprovals(pipelinesNamespace)
  File "/opt/app-root/lib64/python3.9/site-packages/mas/cli/install/app.py", line 1060, in setupApprovals
    for approval in self.approvals.values():
AttributeError: 'InstallApp' object has no attribute 'approvals'
```

**Comment by durera** [comment]
Resolved in:
- https://github.com/ibm-mas/cli/pull/1135 

Fix available in https://github.com/ibm-mas/cli/releases/tag/10.4.2
