### ISSUE TITLE
mas installing is failing with 

### ISSUE THREAD

**Issue by ekambaraml** [ibm-mas/installer#154]
Using the MAS CLI to install the following components

MAS Core
MAS IOT
MAS Manage
MAS Monitor
MAS Predict

The pipeline failed app-cfg-manage task. As below

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/26153008/215553610-b047747a-281f-481e-986e-1ac69f83a3cf.png">
```
ibm.mas_devops.suite_app_config : Configure namespace ------------------- 0.04s
ibm.mas_devops.suite_app_config : Replace xml file with jms_internal_endpoint: {{ jms_internal_endpoint }} --- 0.04s
ibm.mas_devops.suite_app_config : Create Manage app JMS additional server config secrets --- 0.04s
ibm.mas_devops.suite_app_config : Load application variables ------------ 0.04s
Pipeline results not recorded as DEVOPS_MONGO_URI is not defined

```

**Comment by ekambaraml** [comment]
```
oc logs -f dev-monitoragent-88d49f59d-hvhhf 

Caused by: java.net.UnknownHostException: dev-masdev.mas-dev-manage.svc
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at com.ibm.ws.ssl.config.WSSocket.connect(WSSocket.java:260) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253) ~[jersey-bundle-1.19.1.jar:1.19.1]
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153) ~[jersey-bundle-1.19.1.jar:1.19.1]
	... 25 more
17:55:31.612 [Default Executor-thread-11] INFO  com.ibm.monitoring.agent.schedule.TaskScheduler - The MXServer is not yet available. Metric tasks will be scheduled once the server is up.
INFO  TaskScheduler - The MXServer is not yet available. Metric tasks will be scheduled once the server is up.
1
```

**Comment by ekambaraml** [comment]
This is issue repeating all cluster for "app-cfg-manage" pipeline task (STEP-SUITE-APP-CONFIG).

**Comment by ekambaraml** [comment]
Here is a sample setting where it failed.
```
11. Review Settings

    IBM Maximo Application Suite
    Instance ID ............... dev
    Catalog Source ............ ibm-operator-catalog
    Subscription Channel ...... 8.9.x
    IBM Entitled Registry ..... cp.icr.io/cp
    IBM Open Registry ......... icr.io/cpopen
    Entitlement Username ...... cp
    Entitlement Key ........... eyJhbGci<snip>
 
    IBM Maximo Application Suite Applications
    IoT ...................... ibm-operator-catalog/8.6.x
     - Monitor ............... ibm-operator-catalog/8.9.x
    Manage ................... ibm-operator-catalog/8.5.x
     - Predict ............... Skip Installation
    H & P Utilities .......... Skip Installation
    Assist ................... Skip Installation
    MVI ...................... Skip Installation
 
    IBM Suite License Service
    Catalog Source ............ ibm-operator-catalog
    License ID ................ 10005a19dc51
    License File .............. /workspace/entitlement/entitlement.lic
    IBM Entitled Registry ..... cp.icr.io/cp
    IBM Open Registry ......... icr.io/cpopen
    Entitlement Username ...... cp
    Entitlement Key ........... eyJhbGci<snip>
 
    IBM User Data Services
    Contact Email ............. ekambara@us.ibm.com
    First Name ................ Lakshmana
    Last Name ................. Ekambaram
 
    IBM Cloud Pak Foundation Services
    Catalog Source ............ ibm-operator-catalog
 
    Storage Class Configuration
    Storage Class Provider ... ocs
 
Proceed with these settings [y/N] y
```

**Comment by andrercm** [comment]
Hi @ekambaraml have you fixed your problem?
We have enhancements around Manage installation with OOTB JMS server setup to be done within the next development cycles and I'll make sure this is working correctly.

**Comment by andrercm** [comment]
Closing this issue as Manage install via cli passed along with JMS enhancements made in recent cli release 4.0.1:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/31037381/232800134-fc264adc-b292-42de-b066-b9e0eeff7a20.png">
